// <auto-generated />
namespace emp_ferias.lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class overhaul : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(overhaul));
        
        string IMigrationMetadata.Id
        {
            get { return "201606240901089_overhaul"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
